### ISSUE TITLE
Add phone chargers to libservices

### ISSUE THREAD

**Issue by cappadona** [cul-it/signage#1]

**Comment by cappadona** [comment]
All existing 23 phone chargers in the list received from Joanne have been added to `libservices`.

#### Olin (11)
* 1 iPhone 4
* 7 iPhone 
* 3 Micro USB
> [View the live JSON feed](http://mannservices.mannlib.cornell.edu/LibServices/showEquipmentInfo.do?locationId=2&output=json)

#### Uris (12)
* 1 iPhone 4
* 7 iPhone
* 4 Micro USB
> [View the live JSON feed](http://mannservices.mannlib.cornell.edu/LibServices/showEquipmentInfo.do?locationId=18&output=json)

**Comment by manolobevia** [comment]
Thanks Nick for getting these live JSON feeds.
