### ISSUE TITLE
Merge consecutive LibCal bookings by same patron

### ISSUE THREAD

**Issue by cappadona** [cul-it/signage#107]
While working on migrating signs over to the new app the past several weeks, it's becoming pretty clear that that newer LibCal booking UI afforded by the Equipment & Spaces module still mystifies users.

Prior to migrating to the E&S module, we had logic in the legacy app to merge consecutive reservations made by the same patron out of a necessity, but I'm proposing that we introduce similar logic now since many patrons are still submitting separate reservations for any booking that extends the default duration.

Here's an example from earlier today to better illustrate what I'm talking about. Thoughts?

### Current Behavior
![Screenshot_2019-03-06 Mann - Studyrooms(3).png](https://images.zenhubusercontent.com/5615deeb638e718c995da18e/51b8130c-c605-49d2-8b7d-216c8e448218)

### Proposed Behavior (merging consecutive bookings by same patron)
![Screenshot_2019-03-06 Mann - Studyrooms(4).png](https://images.zenhubusercontent.com/5615deeb638e718c995da18e/6a5e2b48-497d-41df-99e9-a0236c8a3b40)

**Comment by sew268** [comment]
@cappadona I agree - let's do it!

**Comment by cappadona** [comment]
Ready to go on [staging](https://signage-stg.herokuapp.com/mann/spaces/studyrooms).

**Comment by cappadona** [comment]
Deployed to production.
