### ISSUE TITLE
Research on fluid typography

### ISSUE THREAD

**Issue by manolobevia** [cul-it/signage#16]
Unlike responsive typography, which changes only at set breakpoints, fluid typography resizes smoothly to match any device width. It is an intuitive option for a web in which we have a practically infinite number of screen sizes included large display which is our case for Olin/Uris Library Signage.

**Comment by manolobevia** [comment]
Currently checking on:
- [ ] Viewport units `vw`, `vh`, `vmin`, `vmax` (<https://www.smashingmagazine.com/2016/05/fluid-typography/>)
- [ ] FitText<http://fittextjs.com/>

**Comment by cappadona** [comment]
Another great reference on Smashing is the [Poly Fluid sizing Sass mixin](https://www.smashingmagazine.com/2017/05/fluid-responsive-typography-css-poly-fluid-sizing).

**Comment by cappadona** [comment]
A couple postcss plugins that implement Mike's original approach:
* [postcss-molten](https://yarnpkg.com/en/packages/postcss-molten)
* [postcss-responsive-type](https://yarnpkg.com/en/package/postcss-responsive-type)

**Comment by manolobevia** [comment]
I am testing the Sass [mixin](https://www.sassmeister.com/gist/7f22e44ace49b5124eec) from
[Fluid Responsive Typography With CSS Poly Fluid Sizing](https://www.smashingmagazine.com/2017/05/fluid-responsive-typography-css-poly-fluid-sizing/). I like the idea of combining viewport units, media queries, and [map ranges](https://rosettacode.org/wiki/Map_range).
