### ISSUE TITLE
Server error displaying on Olin CoLab sign

### ISSUE THREAD

**Issue by miniaturekites** [cul-it/signage#165]
This server error is displaying on the Olin CoLab sign and when I visit http://signage.herokuapp.com/olin/spaces/colab on my Windows desktop.
![IMG_8658](https://user-images.githubusercontent.com/13522344/74965466-4b0c4b80-53e3-11ea-957b-b4adbbda3e76.jpg)

**Comment by tit1** [comment]
@miniaturekites Nick found an issue with the API that was causing the above error and a patch was pushed this morning. I was able to hit the above URL and got a response back. Please feel free to open a new ticket if you have any other issues.
