### ISSUE TITLE
Apply Vue style guide

### ISSUE THREAD

**Issue by cappadona** [cul-it/signage#63]
Clean up on aisle 6!

> https://vuejs.org/v2/style-guide/

**Comment by cappadona** [comment]
Introduced `eslint-plugin-vue` in [7d514e4](https://github.com/cul-it/signage/pull/71/commits/7d514e4e0d22e1d32e46c4b47ce76ad251addfe6#diff-e4403a877d80de653400d88d85e4801aR14) as part of #71 which should make this effort more enjoyable.

**Comment by manolobevia** [comment]
I have to read it again.

**Comment by cappadona** [comment]
All set.
