### ISSUE TITLE
Add consult display for Mann reference

### ISSUE THREAD

**Issue by cappadona** [cul-it/signage#64]
* introduce gray colorway for new status (Reserved)
* use **REFERENCE** for desk name
* use [_Info & Research Help_ hours](https://mannlib.cornell.edu/hours#service-desks)

**Comment by cappadona** [comment]
@tobi Deployed to production.

Two things for your consideration once you've had a chance to review:

1. Use **RESEARCH** for desk name?
    > I had to reduce the font size of the desk name considerably and it's still very tight vs the others

1. I forgot we had previously decided to use the gray color for the **By Appt** status (GIS keeps this status all summer).
   > I was thinking maybe that status label could also work here when open (instead of **Reserved**), and has the added benefit of being shorter so we could again keep a consistent font size with the other desks

![signage dev_mann_consult_reference galaxy tab a 1](https://user-images.githubusercontent.com/409842/33130833-a2180868-cf62-11e7-8d5f-8483d4f8f517.png)

![signage dev_mann_consult_reference galaxy tab a](https://user-images.githubusercontent.com/409842/33130853-adf1e7b2-cf62-11e7-8b2f-910847e0c73c.png)

**Comment by eeh53** [comment]
Thanks, @cappadona! These look great :) See my answers below!

1. I will check with Tom O. on this one. I do see that it's a little bit tight using "REFERENCE", but I'm worried that "RESEARCH" wouldn't be descriptive enough. Tho for that matter, I'm not sure that users know what "reference" means either...

I would love to see what it looks like on the actual tablet in the space, too, to see if the smaller font is an issue.

2. I totally forgot about the GIS "by appt. only", too. I'm not totally sure I follow what you're proposing here. That we say this desk is by appt. only as well? Unfortunately, that's not strictly true - technically they can walk in and get help from the librarian on office hours at that time.

**Comment by cappadona** [comment]
Thanks @eeh53.

1. I hear you, but one could make the case that **Research** might have potential for better connection/recognition since the service point is labeled **Info and Research Help** 😉 

1. I was just thinking out loud and wondering whether using the **By Appt** label could work for this desk as well since my understanding of the primary reasoning for not using **Open** was to prevent consultants from other desks using this space.

Again, these were just thoughts I had as I implemented this. Will close this for now since everything has been implemented as we originally discussed last week. Feel free to reopen if you want any adjustments made.
