### ISSUE TITLE
Implement screen UI from mockup in Nuxt protoype using Susy

### ISSUE THREAD

**Issue by cappadona** [cul-it/signage#7]

**Comment by manolobevia** [comment]
@cappadona Have you checked jeet.gs?

**Comment by cappadona** [comment]
@manolobevia Bookmarked it in 2014 but haven't come back to it recently...looks like it was stagnant for a while but there have been a few commits within the past year. I'm open to checking it out if you find it promising.

**Comment by manolobevia** [comment]
Let's stick with susy2, last commit for jeet was 3 months ago. Not very active repo.

**Comment by cappadona** [comment]
Not that you need more options, but thought you might like [LostGrid](http://lostgrid.org) 😄
