### ISSUE TITLE
Mann B30 Display (basement)

### ISSUE THREAD

**Issue by cappadona** [cul-it/signage#84]
To replace existing [b30display](http://signage.mannlib.cornell.edu/b30display) running in [legacy app](https://github.com/cul-it/b30-display).

**Comment by cappadona** [comment]
@eeh53 @sew268 This is just about ready to go although still ironing out some wrinkles.

One question I have is regarding availability between classes. In the legacy app we had decided to only render an available slot if the buffer was more than 15 minutes, but there was actually a bug in that logic that resulted in requiring at least a 40-minute buffer.

Do you think 15 minutes is enough or should we increase the minimum? There's a good example of this [today in B30A at 11:25am](https://signage-stg.herokuapp.com/mann/spaces/b30). I'm including a screenshot here in case you don't get a chance to review it in the next 45 minutes 😄 

![screenshot_2019-03-06 mann - b30](https://user-images.githubusercontent.com/409842/53893413-29605b80-3ffc-11e9-902e-4623af276cb5.png)

**Comment by eeh53** [comment]
Thanks, @cappadona. I don't recall where that 15 minute buffer we decided on came from. I think it's the bare minimum we would want to allow for the room to show up as available, but honestly, if it's only a 15-min window, is that really enough time to do anything? (I guess students could go in and check their email or something, but I doubt anyone is using the basement classrooms that way) So I would be fine changing that to, say, 30 minutes instead.

**Comment by cappadona** [comment]
You mean you don't remember our decision from [late 2011 / early 2012](https://github.com/cul-it/circ-display/commit/07de229794b9998e37c403e8b5b5590c50233121#diff-c58040b392ee79489c3ee44e52a47c3eR115)? 😉 

Yeah, I agree that 15-minutes is cutting it close to potentially advertise to patrons that public machines are available for their use. I second your suggestion to bumping that minimum up to 30 minutes. What say you, @sew268 ?

**Comment by sew268** [comment]
@cappadona @eeh53 I also don't remember the 15 minute window but agree it's too short.  30 minutes seems more reasonable though even that seems like it might be too short a time frame.  That said, it'll be clear on the display how much time they would have between classes and it is enough time to check email, print, etc.  
Let's go with 30 minutes!

**Comment by cappadona** [comment]
Ha...thanks. We could go with `> 30` instead of `>= 30`. Good compromise?

**Comment by sew268** [comment]
That's the perfect compromise...it's like you've had practice compromising. ;)

**Comment by cappadona** [comment]
The new `> 30 minutes` minimum is now in [play on staging](https://signage-stg.herokuapp.com/mann/spaces/b30) as per #106. Thanks!

**Comment by cappadona** [comment]
Fully pressed and [in production](http://signage.herokuapp.com/mann/spaces/b30).
