### ISSUE TITLE
Mann Bissett Display

### ISSUE THREAD

**Issue by cappadona** [cul-it/signage#85]
To replace existing [bissettdisplay](http://signage.mannlib.cornell.edu/bissettdisplay) running in [legacy app](https://github.com/cul-it/bissett-display).

**Comment by cappadona** [comment]
@eeh53 @sew268 Deployed to staging and ready for your review: https://signage-staging.herokuapp.com/mann/spaces/bissett

Legacy app for comparison: http://signage.mannlib.cornell.edu/bissettdisplay

**Comment by eeh53** [comment]
@cappadona - Looks good, but we're curious what it would look like if we try swapping the text color for the slot background for both available and reserved. Are you willing to give that a try?

**Comment by cappadona** [comment]
Will do...just created #95. Thanks!

**Comment by cappadona** [comment]
[Live on production](http://signage.herokuapp.com/mann/spaces/bissett).
