### ISSUE TITLE
LibCal hours - check if still open from yesterday

### ISSUE THREAD

**Issue by cappadona** [cul-it/signage#89]
For those early morning closing times (past `11:59:59 pm`), which actually fall in the next day. Once 12am hits, the LibCal API call for hours requests the following day, which would result in an inaccurate status of closed.

##### Background/History
This check was [dropped from the legacy app](https://github.com/cul-it/circ-display/pull/39) after switching to LibCal for hours since the LibCal API `api_hours_date` endpoint initially only supported future dates (or today).

When revisiting this today I noticed it now accepts dates in the past, although it's not clear how far back. Initial testing points to maybe only the current week (as of today, Wednesday `2/13/19`, requests for dates prior to Sunday `2/10/19` return null) but if that's the case how do we handle the Saturday to Sunday transition? Stay tuned...

**Comment by cappadona** [comment]
Morning @miniaturekites. Thanks again for adding those late night (early morning) bookings to the CoLab. That really helped me iron out some of the final details and I think we're in pretty good shape.

I would like to test one more edge case. Will you please add several more bookings for the next couple days? Here's what I'm hoping to cover:

* bookings that stop or start at midnight
* bookings that cross over midnight

**Comment by miniaturekites** [comment]
Here are the bookings I made, please let me know if additional bookings would help, they only take a minute to create.

12:00am Wednesday, March 20, 2019 - 12:45am Wednesday, March 20, 2019
	
11:00pm Wednesday, March 20, 2019 - 12:00am Thursday, March 21, 2019
	
11:30pm Thursday, March 21, 2019 - 12:30am Friday, March 22, 2019

**Comment by cappadona** [comment]
Thanks Devin.

If it's not too much trouble, do you mind moving the midnight overlapping booking to tonight since this is the one I expect will be the most challenging? Sorry I wasn't clear about that.

Also we could probably adjust the other two bookings (start/end at midnight) to be consecutive on Wed night into Thurs morning so that we can have each of our conditions/cases covered by Thursday morning 😄.

**Comment by miniaturekites** [comment]
Got it, it should be better now!

**Comment by cappadona** [comment]
Perfect....thank you! And of course the overlapping booking already shows it will be a challenge 😉

**Comment by cappadona** [comment]
One more thing before I forget...

I was able to confirm [my original suspicion from above](https://github.com/cul-it/signage/issues/89#issue-409943641) about requesting hours for dates in the past via the LibCal API.

I've created #115 to provide more details and a proposed solution. Please review and comment there if applicable.

**Comment by cappadona** [comment]
Morning @miniaturekites.

I've refined the logic around early morning closings to address these edge cases and I feel like we've covered all known conditions.

Feel free to take the latest and greatest for a spin on the [staging instance](https://signage-stg-pr-111.herokuapp.com/olin/spaces/colab) and please let me know when you'd like to go live with the Olin CoLab iPad so I can deploy to production.

**Comment by miniaturekites** [comment]
I tested a few more things and noticed some possible bugs:

The page doesn't seem to refresh automatically. I'm not sure if this is an artifact of the staging environment.

I added several appointments with gaps and it seems to only account for one combination of starting time and ending time (e.g. the room shows unavailable at 6:15pm and available again at 8:15pm for the schedule below)

6:15pm Thursday, March 21, 2019 - 7:00pm Thursday, March 21, 2019
7:45pm Thursday, March 21, 2019 - 8:15pm Thursday, March 21, 2019
9:15pm Thursday, March 21, 2019 - 9:30pm Thursday, March 21, 2019
11:45pm Thursday, March 21, 2019 - 12:30am Friday, March 22, 2019

**Comment by cappadona** [comment]
Hi Devin.

Thanks for the feedback. Quick response to your two potential bugs:

1. I'm not able to reproduce. Staging instance is refreshing date on expected intervals. Can you provide additional details on what makes you think that this is not happening on your end?

1. Definitely a bug, introduced in an enhancement implemented after my comment from this morning (#116). Thanks for catching this 👍  I see what's up and will submit a patch shortly.

**Comment by cappadona** [comment]
Okay Devin...[patch has been applied for your second issue](https://github.com/cul-it/signage/pull/117) and [review app has been spun up](https://signage-stg-pr-117.herokuapp.com/olin/spaces/colab).

Thanks again. Looking forward to hearing from you.

**Comment by miniaturekites** [comment]
1. The clock in the upper right doesn't update, it still says 4:32 and it's now 4:50.

2. That fox looks good to me, thank you!

**Comment by cappadona** [comment]
Thanks for clarifying on number 1. Is this on the iPad? Using the Kiosk app or just in Safari? Any details you can provide will help. I'm still unable to reproduce locally on my laptop 😄

**Comment by cappadona** [comment]
Quick update...just ran to get my iPad and **I am able to reproduce** your observed behavior (time is not refreshing).

It's not immediately obvious to me why the underlying code behind the refresh isn't triggering in the older mobile Safari browser, but I will take a closer look tomorrow and let you know what I find.

**Comment by miniaturekites** [comment]
Sorry, yes, this is the built in version of Safari on the iPad (iOS 9.3.5, the latest available for this iPad 2) and the Kiosk app appears to match (in this case I tested from 5:08 until 5:16)

**Comment by miniaturekites** [comment]
I appreciate it, thank you!

**Comment by cappadona** [comment]
Morning @miniaturekites. We should be back in business with the older iPads refreshing content (#118). Please let me know if you find otherwise.

**Comment by miniaturekites** [comment]
Looks good, the page refreshes, the clock updates, and new appointments "appear" on their own. I think we're ready to go!

**Comment by cappadona** [comment]
Great...I'll get everything merged and let you know once I've deployed to production.

**Comment by cappadona** [comment]
Deployed to production. Thanks for the huge assist, @miniaturekites 🤗 

https://signage.library.cornell.edu/olin/spaces/colab
