### ISSUE TITLE
Investigate fallback to css-grid for legacy browsers

### ISSUE THREAD

**Issue by cappadona** [cul-it/signage#94]
Primarily to address use of older iPads at Olin which max out at iOS `9.3.5`.

Since this is in response to Devin's request for Olin CoLab Display #87, which only covers 1 space (single column), will focus on grid used for header (datetime and reserve URL).

> [browser support for css-grid](https://caniuse.com/#feat=css-grid)

**Comment by cappadona** [comment]
Hi @miniaturekites. Finally had a chance to work on this today. Will you try bringing up the Olin Colab sign at this URL on one of your iPads and let me know how it looks? Thanks.

https://signage-stg-pr-110.herokuapp.com/olin/spaces/colab

**Comment by cappadona** [comment]
### Response from Devin

> Hi Nick,
>
> Thank you for working on this, the spacing of the date, room title, and current time looks great! Is it pulling data from the live version of LibCal? I see bookings on this part of LibCal: https://spaces.library.cornell.edu/admin/spaces/bookings?gid=10984 but they don’t show up on the staging link you sent and I want to make sure I’m doing the LibCal part correctly.
>
> Devin

**Comment by cappadona** [comment]
Thanks for the feedback @miniaturekites.

Yes, that's the same space (based on the space ID) that I have in the schema for the signage app. I see what the issue is...I have [logic that filters out bookings based on the status](https://github.com/cul-it/signage/blob/c15da10017204cd7e16a9b3d27c2670d215892b8/utils/libcal.js#L95), but it's too strict and doesn't account for mediated spaces.

I'll tweak that and send another heads up when it's ready for you to review.

**Comment by cappadona** [comment]
Alright @miniaturekites. Please [take another look](https://signage-stg-pr-110.herokuapp.com/olin/spaces/colab) when you get a chance.

**Comment by miniaturekites** [comment]
Looks fabulous, thank you!

**Comment by cappadona** [comment]
Great. Thanks for confirming. Going to merge this now and get it deployed to the staging instance. When do you plan on going live with the CoLab sign?

**Comment by miniaturekites** [comment]
We're ready to go live whenever it's ready in the main system.

**Comment by cappadona** [comment]
That's great. I just [pushed an enhancement](https://github.com/cul-it/signage/pull/111) to handle early morning closing times (#89), which is necessary to handle the CoLab with its 2am closing Sun - Thu.

I've done some preliminary testing but are you willing to help me out with additional testing by creating some early morning bookings (after midnight) for Monday 3/18 and Tuesday 3/19?

As for going live with the sign, what's your preference between these two options?

1. Deploy the current staging version as is to production right now

   > it will not include the early morning closing times, so on Sunday night the CoLab sign will report as being closed at the strike of midnight),

1. Point the iPad to the [review app for this new enhancement](https://signage-stg-pr-111.herokuapp.com/olin/spaces/colab)

   > the CoLab sign will continue to display as open after midnight and up to 2am as applicable and we'll be testing the schedule builder live in the wild 😄

**Comment by miniaturekites** [comment]
I've created some appointments in the early morning on those days. As for the two options, will the URL in choice 2 change? I'd rather wait until the the fix for 12-2am is on a stable URL.

**Comment by cappadona** [comment]
Yes, the URL will change for option 2, sorry that wasn't clear.

The current production URL is https://signage.herokuapp.com/olin/spaces/colab, but I'd hesitate to even call that _stable_ just yet as I'm making a push to register a subdomain of `library.cornell.edu` for the application.

**Comment by cappadona** [comment]
P.S. Thanks for adding those test bookings...especially for the variance 👍 

Is it safe to assume you want to go with Door C and wait to go live with the CoLab sign until next week once we've have a chance to put the still open from yesterday enhancement through its paces?

**Comment by miniaturekites** [comment]
Yes, I'd like to wait for that enhancement and I'm also hesitant about deploying anything on a Friday afternoon when I won't be able to monitor it over the weekend. :)

**Comment by cappadona** [comment]
Couldn't agree with you more 😄 .

I'll touch base early next week to let you know where we stand. Thanks for your patience.

Have a good one.

**Comment by cappadona** [comment]
Layout is all set so closing this one out. Work continues on early morning closings in #89.
