### ISSUE TITLE
Coordinate with Matt to update URLs on Mann devices

### ISSUE THREAD

**Issue by cappadona** [cul-it/signage#97]
Need to point to the new production URLs for the migrated signs.

**Comment by cappadona** [comment]
Hey @mrr15.

We didn't get a chance to cover this during yesterday's MaLT meeting before you needed to leave. All of the signs that were designated for migration are live and ready to go, so we should touch base and figure out a schedule for updating the devices to point to the new URLs.

Let me know what works for you when you get a chance.

### Migrated signs

* [B30](https://signage.library.cornell.edu/mann/spaces/b30)
* [Bissett Workstations](https://signage.library.cornell.edu/mann/spaces/bissett)
* [Interview Room](https://signage.library.cornell.edu/mann/spaces/interview)
* [Room 261](https://signage.library.cornell.edu/mann/spaces/room261)

### Existing signs with updated URLs

* [Study Rooms](https://signage.library.cornell.edu/mann/spaces/studyrooms)
* [mannUfactory Multimedia Studio](https://signage.library.cornell.edu/mannufactory/spaces/multimedia)
* All Consultation desks

> Should I pull in Tom and Jimmy for mannUfactory and Consultation desks?

**Comment by tit1** [comment]
Consult area is completed. Im in the process of swapping out the ipad displays for Android, but i need more licenses for the software. I shared all passwords with those concerned via lastpass.

**Comment by tit1** [comment]
Multimedia room is in place.. I will work with Jimmy and Sara on final placement.

**Comment by tit1** [comment]
261 has been changed over but it looks like it needs a new power supply.. @mrr15  we will have to change it out later this week..

**Comment by cappadona** [comment]
Thanks Tom!

**Comment by cappadona** [comment]
Morning @mrr15 & @tit1. Are we all set with these?

**Comment by cappadona** [comment]
Hi again @mrr15 & @tit1. Can we stick a fork in this or is the interview room still being difficult?

**Comment by tit1** [comment]
There is still an issue with the sign but it is hardware; i think a bad power supply.  We did change out one but i need to take a closer look as to whats going on.

**Comment by cappadona** [comment]
Thanks for the update @tit1 😃
